# Generated by Django 5.0 on 2024-02-21 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="noteshare",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_with_users",
                to="notes.note",
            ),
        ),
        migrations.AddField(
            model_name="noteshare",
            name="shared_with",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="share_notes",
                through="notes.NoteShare",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="noteversionhistory",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="notes.note",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noteshare",
            unique_together={("note", "shared_with")},
        ),
    ]
